services:
  router-client-list:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: python src/asus_router_client_list.py