version: '3.8'

services:
  router-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: python src/asus_router_client_list.py